- name: Hello World Sample
  hosts: all
  tasks:

    - name: Send notification to Slack
      wait_for:
        timeout: 240
      delegate_to: localhost
      no_log: true
      
    - name: Send notification to Slack
      debug:
        msg: "The application is deployed successfully"
