- name: Hello World Sample
  hosts: all
  tasks:
    - name: Send notification to Slack
      debug:
        msg: "The application is deployed successfully"


    - name: Sleep for 300 seconds and continue with play
      wait_for:
        timeout: 240
      delegate_to: localhost
      no_log: true
